config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'posts#index'
  get "posts/my_posts", to: "posts#my_posts", as: :my_profile
  resources :categories

  resources :chatrooms do
    resources :messages, only: :create
  end

  resources :posts do
    resources :likes
    resources :reviews
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  skip_after_action :verify_policy_scoped, only: :index

  def index
    @chatrooms = Chatroom.all
    authorize @chatrooms
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
    authorize @chatroom
  end

  def new
    @chatroom = Chatroom.new
    authorize @chatroom
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
    authorize @chatroom
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @chatroom = Chatroom.find(params[:id])
    authorize @chatroom
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def chatroom_params
    params.require(:chatroom).permit(:name)
  end
end

app/views/chatrooms/_form.html.erb
<%= simple_form_for(@chatroom) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">

      <h1>Editing Chatroom</h1>

      <%= render 'form', chatroom: @chatroom %>

      <%= link_to 'Show', @chatroom %> |
      <%= link_to 'Back', chatrooms_path %>
    </div>
  </div>
</div>

app/views/chatrooms/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Chatrooms</h1>
  <div class="row">
    <div class="col-md-12">
    <div class="row">


      <% @chatrooms.each do |chatroom| %>
        <div class="col-md-6">
          <div class="card mt-3">
            <div class="card-body">
              <h4><%= link_to chatroom.name, chatroom_path(chatroom.id) %></h4>
              <%= link_to "Join", chatroom_path(chatroom.id), class: "btn btn-primary"  %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    </div>
<br>

  </div>
  <div class='mt-3 mb-2'>
    <% if policy(Chatroom).create? %>
      <%= link_to 'Create Chatroom', new_chatroom_path, class: 'btn btn-info' %>
    <% end %>
  </div>
  <%= link_to 'Back', root_path, class: 'btn btn-secondary' %>
</div>

app/views/chatrooms/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">

      <h1>New Chatroom</h1>

      <%= render 'form', chatroom: @chatroom %>

      <%= link_to 'Back', chatrooms_path %>
    </div>
  </div>
</div>

app/views/chatrooms/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="chat-header"><h4>#<%= @chatroom.name %></h4></div>
        <div id="messages" data-chatroom-id="<%= @chatroom.id %>">
          <% @chatroom.messages.each do |message| %>
            <div class="message-container" id="message-<%= message.id %>">
              <i class="author">
                <span><%= message.user.nickname %></span>
                <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
              </i>
              <p><%= message.content %></p>
            </div>
          <% end %>
        </div>

        <div id="create-message">
          <%= simple_form_for [ @chatroom, @message ], remote: true do |f| %>
            <%= f.input :content, label: false, placeholder: "type a message in ##{@chatroom.name} channel" %>
            <div class = 'mt-3'>
              <%= f.button :submit, 'Send Message', class: 'btn btn-secondary' %>
            </div>
          <% end %>
        </div>
        <%= link_to 'Back', chatrooms_path %>
    </div>
  </div>
</div>