config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'posts#index'
  get "posts/my_posts", to: "posts#my_posts", as: :my_profile
  resources :categories

  resources :chatrooms do
    resources :messages, only: :create
  end

  resources :posts do
    resources :likes
    resources :reviews
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/harrytimbog/"><i class="fab fa-instagram"></i></a>
    <a href="https://web.facebook.com/arigbedetimilehin"><i class="fab fa-facebook"></i></a>
    <a href="https://www.linkedin.com/in/timilehin-arigbede-227449144/"><i class="fab fa-linkedin"></i></a>
    <a href="https://wa.me/2348132930847"><i class="fab fa-whatsapp"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"> by Harrytimbog</i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand fas fa-home" do %>
    <h1>HARRIE'S BLOG</h1>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.try(:admin?) %>
          <li class="nav-item mr-2">
            <%= link_to "Admin Dashboard", rails_admin_path, class: "nav-link btn btn-outline-info" %>
          </li>
        <% end %>
        <li class="nav-item mr-2">
          <%= link_to "Messages", chatrooms_path, class: "nav-link btn btn-outline-primary" %>
        </li>
        <li class="nav-item mr-2">
          <%= link_to "Create A Post", new_post_path, class: "nav-link btn btn-primary" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", my_profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          <% else %>
              <% avatar_url = current_user.picture_url || "http://placehold.it/30x30" %>
              <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

              <%= link_to "My Profile", my_profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% end %>

        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>