config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'posts#index'
  get "posts/my_posts", to: "posts#my_posts", as: :my_profile
  resources :categories

  resources :chatrooms do
    resources :messages, only: :create
  end

  resources :posts do
    resources :likes
    resources :reviews
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :owner, class_name: "User"
  has_many_attached :photos
  validates :title, :rich_body, presence: true
  has_rich_text :rich_body
  has_many :reviews, dependent: :destroy
  belongs_to :category
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  STATUSES = ["drafted", "completed"]
  validates :status, inclusion: {in: STATUSES}

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  skip_after_action :verify_policy_scoped, only: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @categories = Category.all

    cate = params[:cate]

    if !cate.nil?
      @posts = Post.where(category_id: cate)
    else
      @posts = policy_scope(Post).order(created_at: :desc)
    end
    authorize @posts
  end

  # GET /posts/1
  def show
    @review = Review.new
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
    authorize @post
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.owner = current_user

    if @post.save
      redirect_to post_path(@post), notice: 'post was successfully created.'
    else
      render :new
    end
    authorize @post
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'post was successfully updated.'
    else
      render :edit
    end
    authorize @post
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'post was successfully destroyed.'
    authorize @post
  end

  def my_posts
    @my_posts = Post.where(owner_id: current_user.id)
    authorize @my_posts
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end

  # Only allow a trusted parameter "white list" through.
  def post_params
    params.require(:post).permit(:title, :status, :rich_body, :category_id, photos: [])
  end
end

app/views/posts/_form.html.erb
<div class="flex-row d-flex justify-content-center m-1">
  <div class="card mt-1">
    <div class="card-body">

      <%= simple_form_for(@post) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="row">
          <div class="col-xs-6 mr-5">
            <h3><%= f.input :title, placeholder: "Title of you post" %></h3>
          </div>
          <div class="col-xs-6">
            <h3>
              <%= f.input :status, collection: Post::STATUSES, prompt: "Which status?" %>
            </h3>
          </div>
        </div>
        <div class="form-group">
          <input type="hidden" name="post[category_id]" value="">
          <div class="category-choices m-1">

            <% Category.all.each do |category| %>

              <input type="checkbox" class="hidden" style="display:none" value="<%= category.id  %>"
              name="post[category_id]" id="post_category_id_<%= category.id %>">

              <label class="category-choice" for="post_category_id_<%= category.id  %>">
                <p>
                  <%= category.name %>
                </p>
                <i class="fa fa-check"></i>
              </label>
            <% end %>
          </div>
        </div>

      <!--
        <div class="form-inputs">
          <%= f.select :category, Category.all.map {|c| c.name } %>
        </div>
      !-->

        <div class="form-inputs">
          <h3>
             <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          </h3>
        </div>

        <div class="form-inputs">
          <%= f.rich_text_area :rich_body, placeholder: "Give us the full Gist" %>
        </div>

        <br>
        <div class="form-actions">
          <%= f.button :submit, "save your post", class: "btn btn-primary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/posts/_search_bar.html.erb
<%= form_tag posts_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a post"
  %>
  <%= submit_tag "Search", class: "hide-me btn btn-primary waves-light waves-effect mt-1" %>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="form-post">
        <h1>Editing Post</h1>

        <%= render 'form', post: @post %>

        <%= link_to 'Show', @post %> |
        <%= link_to 'Back', root_path %>

      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1 class="text-center">Posts</h1>
  <div class="row">
    <div class="col-md-4">

      <div class="card mt-3">
        <div class="card-header">
          <h3> <%= link_to 'CATEGORIES', categories_path, class: 'btn btn-outline-primary' %></h3>
        </div>

        <div class="card-body">
          <%  @categories.each do |category| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <%= link_to category.name, posts_path(cate: category.id)   %>
            <span class="badge badge-primary badge-pill"> <%= category.posts.count %> </span>
          </li>
          <% end %>
        </div>
      </div>
      <div class='mt-2'>
        <% if policy(Post).create? %>
          <%= link_to 'Create Your Own Post', new_post_path, class: 'btn btn-primary btn-lg btn-block' %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8">
    <div class="row">


      <% @posts.each do |post| %>
        <div class="col-md-6">
          <div class="card mt-3">
            <div class="card-body">
              <div class="d-flex justify-content-between">
                <div>
                  <h4 class='card-title'><%= link_to post.title, post_path(post.id) %></h4>
                </div>
                <% if post.owner.avatar.attached? %>
                  <div>
                    <%= cl_image_tag post.owner.avatar.key, class: "avatar" %>
                  </div>
                <% end %>
              </div>

              <%= link_to "View", post_path(post.id), class: "btn btn-primary"  %>
              <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
              <i>
                <small>Posted by <%= post.owner.nickname  %></small>
              </i>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    </div>
  </div>
  <br>

</div>
<%= render "shared/footer" %>

app/views/posts/my_own.html.erb
<div class="main m-4">
  <div class="container">

      <%= cl_image_tag @current_user.avatar.key, width: 300, height: 250, crop: :fill, :quality=>"auto", :fetch_format=>:auto, class: "rounded-circle" %>
    <h3>Hi <%= current_user.nickname %></h3>
    <% if @my_posts.empty? %>
      <p>You haven't created any post yet.................</p>
    <% else %>
        <p>Here are your posts</p>

        <ul class="list-group col-12 col-md-6 col-lg-3">
          <div class="row">
            <% @my_posts.each do |post| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <span class="badge badge-primary badge-pill">
                  <%= post.title %>
                </span>
                <%= post.title %>
              </li>
            <% end %>
          </div>
        </ul>
    <% end %>
  </div>
  <%= link_to "back", root_path %>
  <br>
  <br>
  <br>
</div>

app/views/posts/my_posts.html.erb
<div class="main m-4">
  <div class="container">
    <% if current_user.avatar.attached? %>
      <%= cl_image_tag @current_user.avatar.key, width: 300, height: 250, crop: :fill, :quality=>"auto", :fetch_format=>:auto, class: "rounded-circle" %>
    <% end %>

    <h3>Hi <%= current_user.nickname %></h3>
    <div class='text-right'>
      <div class='badge badge-primary text-wrap'>
        <i>You Joined this Platform on <%= current_user.created_at.strftime("%a %b %e at %l:%M%p") %></i>
      </div>
    </div>
    <% if @my_posts.empty? %>
      <p>You haven't created any post yet.................</p>
    <% else %>
        <p>Here are your posts</p>

        <ul class="list-group col-12 col-md-6 col-lg-3">
          <div class="row">
            <% @my_posts.each do |post| %>
              <li class="list-group-item d-flex justify-content-between align-items-center m-1">
                <span>
                  <%=link_to post.title, post_path(post.id) %>
                </span>
              </li>
            <% end %>
          </div>
        </ul>
    <% end %>
  </div>
  <div class='mt-2'>
    <%= link_to "Make changes to your profile", edit_user_registration_path, class: 'btn btn-success' %>
  </div>
  <div class='mt-2'>
    <%= link_to "back", root_path, class: 'btn btn-dark' %>
  </div>
  <br>
  <br>
  <br>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="form-post">
        <h1>Write a post</h1>

        <%= render 'form', post: @post %>

        <%= link_to 'Back', root_path %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for :meta_title, "#{@post.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @post.rich_body %>

<!--POST DETAILS!-->

<div class="container">
  <p id="notice"><%= notice %></p>

   <h3>Category: <%= @post.category.name %></h3>
  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @post.rich_body %>
  </p>
  <% @post.photos.each do |photo| %>
    <%= cl_image_tag photo.key, height: 300, width: 350, crop: :fill, :quality=>"auto", :fetch_format=>:auto, class: 'm-1 text-center' %>
  <% end %>

  <div class='text-right'>
    <div class='badge badge-primary text-wrap'>
      <i><%=@post.status %> and created by <%=@post.owner.nickname %> on <%= @post.owner.created_at.strftime("%a %b %e at %l:%M%p") %> </i>
    </div>
    <div class='m-3'>
    <% unless !user_signed_in? %>
      <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
      <% if pre_like %>
        <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete, class: 'fas fa-thumbs-down' %>
      <% else %>
        <%= link_to ' Like', post_likes_path(@post), method: :post, class: 'fas fa-thumbs-up' %>
      <% end %>
      <p><%= pluralize @post.likes.size, "Like" %></p>
    <% else %>
      <p><%= pluralize @post.likes.size, "Like" %></p>
    <% end %>
    </div>
  </div>


  <!--POST COMMENTS!-->

  <h4>Comments</h4>
  <% unless !user_signed_in? %>
    <% pre_comment = @post.comments.find { |comment| comment.user_id == current_user.id} %>
    <% if @post.comments.empty? %>
      <p>Be the first to add a comment</p>
    <% else %>
      <ul class="list-group">
        <% @post.comments.each do |comment| %>
          <li class="list-group-item d-flex align-items-center mt-2">
            <p id="comment-<%= comment.id %>"><%= comment.content %></p>
          </li>
          <small>by <%= comment.user.nickname  %></small>
        <% end %>
      </ul>
      <% if pre_comment %>
        <%= button_to 'Delete Comment', post_comment_path(@post, pre_comment), method: :delete, remote: true %>
      <% end %>
    <% end %>
  <% else %>
    <ul class="list-group">
      <% @post.comments.each do |comment| %>
        <li class="list-group-item d-flex align-items-center mt-2">
          <p id="comment-<%= comment.id %>"><%= comment.content %></p>
        </li>
        <small>by <%= comment.user.nickname  %></small>
      <% end %>
    </ul>
  <% end %>

  <%= render "comments/new", post: @post, comment: @comment %>


  <!--POST REVIEWS!-->


  <h4>Reviews</h4>
  <% unless !user_signed_in? %>
    <% pre_review = @post.reviews.find { |review| review.user_id == current_user.id} %>
    <% if @post.reviews.empty? %>
      <p>Be the first to add a review</p>
    <% else %>
      <ul class="list-group">
        <% @post.reviews.each do |review| %>
          <li class="list-group-item d-flex justify-content-between align-items-center mt-2">
            <span class="badge badge-primary badge-pill">
              <% counter = 0 %>
              <% 5.times do %>
                <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                <% counter += 1 %>
              <% end %>
            </span>
            <p id="review-<%= review.id %>"><%= review.content %></p>
          </li>
          <small>by <%= review.user.nickname  %></small>
        <% end %>
      </ul>
      <% if pre_review %>
        <%= button_to 'Delete Review', post_review_path(@post, pre_review), method: :delete, remote: true %>
      <% end %>
    <% end %>
  <% else %>
    <ul class="list-group">
      <% @post.reviews.each do |review| %>
        <li class="list-group-item d-flex justify-content-between align-items-center mt-2">
          <span class="badge badge-primary badge-pill">
            <% counter = 0 %>
            <% 5.times do %>
              <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
              <% counter += 1 %>
            <% end %>
          </span>
          <p id="review-<%= review.id %>"><%= review.content %></p>
        </li>
        <small>by <%= review.user.nickname  %></small>
      <% end %>
    </ul>
  <% end %>

  <small> <%= pluralize @post.reviews.size, "Review" %></small>

  <%= render "reviews/new", post: @post, review: @review %>

<div class='mt-2 mb-2'>
  <% if current_user.try(:admin?) || current_user == @post.owner %>
    <% if policy(@post).edit? %>
      <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-outline-primary" %> |
    <% end %>
    <% if policy(@post).destroy? %>
      <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %> |
    <% end %>
  <% end %>
    <%= link_to 'Back', root_path, class: 'btn btn-secondary' %>
  </div>
</div>