config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'posts#index'
  get "posts/my_posts", to: "posts#my_posts", as: :my_profile
  resources :categories

  resources :chatrooms do
    resources :messages, only: :create
  end

  resources :posts do
    resources :likes
    resources :reviews
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories
  has_many :posts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_after_action :verify_policy_scoped, only: :index
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    authorize @categories
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize @category
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
    authorize @category
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
    authorize @category
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">

      <h1>Editing Category</h1>

      <%= render 'form', category: @category %>

      <%= link_to 'Show', @category %> |
      <%= link_to 'Back', categories_path %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Categories</h1>
  <div class="row">
    <div class="col-md-12">
    <div class="row">


      <% @categories.each do |category| %>
        <div class="col-md-6">
          <div class="card mt-3">
            <div class="card-body">
              <h4><%= link_to category.name, category_path(category.id) %></h4>
              <%= link_to "View", category_path(category.id), class: "btn btn-primary"  %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    </div>
<br>

  </div>
  <div class='mt-3 mb-3'>
    <% if policy(Category).create? %>
      <%= link_to 'New Category', new_category_path, class: 'btn btn-info' %> |
    <% end %>
    <%= link_to 'Back', root_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">

      <h1>New Category</h1>

      <%= render 'form', category: @category %>

      <%= link_to 'Back', categories_path %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">

      <p id="notice"><%= notice %></p>

      <p>
        <strong>Name:</strong>
        <%= @category.name %>
      </p>

      <% if policy(@category).edit? %>
        <%= link_to 'Edit', edit_category_path(@category), class: "btn btn-outline-primary" %> |
      <% end %>
      <% if policy(@category).destroy? %>
        <%= link_to 'Delete', category_path(@category), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %> |
      <% end %>
        <%= link_to 'Back', categories_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>


</div>